# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.dtauh.com:
  peer0.org1.dtauh.com:
  peer0.org2.dtauh.com:
  peer0.org3.dtauh.com:

networks:
  dtauhnetwork:

services:

  orderer.dtauh.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.dtauh.com
    container_name: orderer.dtauh.com
    networks:
      - dtauhnetwork

  peer0.org1.dtauh.com:
    container_name: peer0.org1.dtauh.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.dtauh.com
    networks:
      - dtauhnetwork

  peer0.org2.dtauh.com:
    container_name: peer0.org2.dtauh.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.dtauh.com
    networks:
      - dtauhnetwork

  peer0.org3.dtauh.com:
    container_name: peer0.org3.dtauh.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.dtauh.com
    networks:
      - dtauhnetwork

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.dtauh.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dtauh.com/peers/peer0.org1.dtauh.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dtauh.com/peers/peer0.org1.dtauh.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dtauh.com/peers/peer0.org1.dtauh.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dtauh.com/users/Admin@org1.dtauh.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.dtauh.com
      - peer0.org1.dtauh.com
      - peer0.org2.dtauh.com
      - peer0.org3.dtauh.com
    networks:
      - dtauhnetwork
